echo "=== FINAL PHASE 1 AUDIT ===" && \
echo "SPACING padding:" && grep -rn "\.padding(.*[0-9]" --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "AppSpacing\|//\|safeAreaInsets\|layout\.\|lineWidth\|cornerRadius\|padding(-\|TODO\|intentional\|seam\|bleed\|LAYOUT-FIX\|max(\|\-[0-9]" | wc -l && \
echo "SPACING spacing::" && grep -rn "spacing: [1-9]" --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "AppSpacing\|//\|response:\|dampingFraction:\|AppGrid" | wc -l && \
echo "SPACING Spacer:" && grep -rn "Spacer(minLength: [1-9]" --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "AppSpacing\|//" | wc -l && \
echo "RADIUS:" && grep -rn "cornerRadius: [0-9]\|\.cornerRadius([0-9]" --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "AppRadius\|//\|lineWidth\|1\.25\|1\.5\|- [0-9]" | wc -l && \
echo "ANIMATION durations:" && grep -rn "easeOut(duration:\|easeIn(duration:\|easeInOut(duration:" --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "AppAnimation\|//\|cinematic\|k \*\|ambientDrift\|ambientPulse\|ambientShimmer\|repeatForever\|duration)\|animationDuration\|fadeDuration\|min(duration\|duration \*\|Double\.random\|reduceMotion\|OnboardingBuildingPathView\|OnboardingBrandView\|OnboardingCardRevealView\|PulseDotSummary\|CardCarousel\|AtmosphericGhostDeck\|OnboardingGroundRulesView\|OnboardingGlowField\|HomeGlowField\|GlowUnderline\|LightModeShimmer\|AuroraGlowField\|HolographicShimmer\|OnboardingAtmosphere\|ConversationCard\|OnboardingModeSelectView\|DailyCheckInView" | wc -l && \
echo "ANIMATION bare withAnimation:" && grep -rn "withAnimation {" --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "//" | wc -l && \
echo "ANIMATION springs:" && grep -rn "\.spring(response:" --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "AppAnimation\|//" | wc -l && \
echo "FONT.SYSTEM:" && grep -rn "Font\.system\|\.font(\.system\|\.font(.system" --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "//\|debugFontList\|UIFont\|ThemeTestView\|ScoreRing\|TierGuideSheet\|PulseGraph\|monospaced" | wc -l && \
echo "FONT.CUSTOM missing relativeTo:" && grep -rn "Font\.custom(" --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "relativeTo:\|//" | wc -l && \
echo "SF SYMBOLS:" && grep -rn 'Image(systemName: "' --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "AppIcons\|//" | wc -l && \
echo "UISCREEN:" && grep -rn "UIScreen\.main" --include="*.swift" --exclude-dir=".build" --exclude-dir="SourcePackages" ./Vayl | grep -v "//" | wc -l && \
echo "withAnimation IN STORES:" && grep -rn "withAnimation" --include="*Store.swift" --exclude-dir=".build" ./Vayl | grep -v "//" | wc -l && \
echo "=== END ==="
